apiVersion: someteam.example.com/v1
kind: JinjaTransformer
metadata:
  name: function-ephemeral-secret
jinjaTemplate: |
  {% set source = fn.filter_getMatchingIndexes(resources,
                fn.filter_operatorAnd(
                        fn.filter_fieldEqual("kind", "VariableCatalogue"),
                        fn.filter_fieldEqual("metadata/name", "function-ephemeral-secret")
                )[0] %}
  {{ 
        resources | 
        filter_modifyMatching(
                fn.filter_operatorAnd(
                        fn.filter_fieldEqual("kind", "Secret"),
                        fn.filter_fieldEqual("metadata/name", "node1-bmc-secret")
                ),
                fn.modify_byPath(
                        "stringData/userData|write_files/0/content|clusters/0/cluster/certificate-authority-data",
                        "updated {}".format(fn.operation_set(source.spec.kubernetes.ca))
                )
        ) |
        yaml_dump(_all=True)
  }}
