dist: bionic
language: python
python:
- "3.6"
install:
- (cd bin && pwd && curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash)
script:
- PATH="$PATH:$(pwd)/bin" ./demo
