#!/bin/bash
#env
echo "**************************Generator demo output**************************"
JINJA_CRYPT_PASSWORD="multipass" JINJA_DEBUG=0 XDG_CONFIG_HOME=$(pwd) kustomize build --enable_alpha_plugins overlays/crypt

echo "**************************Catalog demo output****************************"
JINJA_CRYPT_PASSWORD="multipass" JINJA_DEBUG=0 XDG_CONFIG_HOME=$(pwd) kustomize build --enable_alpha_plugins overlays/catalogs

echo "**************************Transformer demo 1 output**********************"
JINJA_DEBUG=0 XDG_CONFIG_HOME=$(pwd) kustomize build --enable_alpha_plugins overlays/transformer1

echo "**************************Transformer demo 2 output**********************"
JINJA_DEBUG=0 XDG_CONFIG_HOME=$(pwd) kustomize build --enable_alpha_plugins overlays/transformer2

echo "**************************Transformer demo 3 output**********************"
JINJA_DEBUG=0 XDG_CONFIG_HOME=$(pwd) kustomize build --enable_alpha_plugins overlays/transformer3

echo "**************************Demo with several layers***********************"
JINJA_DEBUG=0 XDG_CONFIG_HOME=$(pwd) kustomize build --enable_alpha_plugins manifests/site/test-bootstrap/ephemeral/
