apiVersion: v1
kind: Secret
metadata:
  labels:
    airshipit.org/ephemeral-user-data: "true"
  name: node1-bmc-secret
type: Opaque
stringData:
  userData: |
    bootcmd:
    - mkdir /mnt/vda
    - mount /dev/vda /mnt/vda
    - mkdir -p /opt/metal3-dev-env/ironic/html/images
