apiVersion: someteam.example.com/v1
kind: JinjaTransformer
metadata:
  name: transform-dev-ephemeral-network-data2
sources:
- path: jinjacatalog.yaml
jinjaTemplate: |
  {{ 
        resources | 
        filter_modifyMatching(
                fn.filter_operatorAnd(
                        fn.filter_fieldEqual("kind", "Secret"),
                        fn.filter_fieldEqual("metadata/name", "dev-node1-bmc-secret-v1")
                ),
                fn.modify_byPath(
                        "stringData/userData|bootcmd/0",
                        fn.operation_set(
                                "/usr/sbin/mkfs.ext4 /dev/vda --param {}".format(config.sources[0].object.data.name_base)
                        )
                )
        ) |
        yaml_dump(_all=True)
  }}
