apiVersion: someteam.example.com/v1
kind: JinjaTransformer
metadata:
  name: transform-dev-ephemeral-network-data2
jinjaCatalog: jinjacatalog.yaml
jinjaTemplate: |
  {{ functions.yaml_dump(
        functions.filter_modifyMatching(
                resources,
                functions.filter_operatorAnd(
                        functions.filter_fieldEqual("kind", "Secret"),
                        functions.filter_fieldEqual("metadata/name", "dev-node1-bmc-secret-v1")
                ),
                functions.modify_byPath(
                        "stringData/userData|bootcmd/0",
                        functions.operation_set(
                                "/usr/sbin/mkfs.ext4 /dev/vda --param {}".format(catalog.data.name_base)
                        )
                ),
        ),
        _all=True
     ) }}
