resources:
- ../../base
- jinjacatalog.yaml
namePrefix: dev-
nameSuffix: -v1
configMapGenerator:
- name: my-configmap
  behavior: merge
  files:
  - plumbing.properties
  - secret.properties
generators:
- testJinjaGenerator.yaml
transformers:
- jinjacatalog.yaml
