apiVersion: someteam.example.com/v1
kind: JinjaTransformer
metadata:
  name: whatever
jinjaCatalog: jinjacatalog.yaml
jinjaTemplate: |
  {% for i in resources %}
  {% if 'dev-jinja-configmap-test-v1' == i.metadata.name %}
  {{    functions.yaml_dump(functions.dict_update(i, catalog.data)) }}
  {% else %}
  {{    functions.yaml_dump(i) }}
  {% endif %}
  ---
  {% endfor %}
