apiVersion: someteam.example.com/v1
kind: JinjaGenerator
metadata:
  name: whatever
jinjaCatalog: jinjacatalog.yaml
jinjaTemplate: |
  {{ functions.catalog_render("overlay-y", data) }}
  ---
  kind: ConfigMap
  apiVersion: v1
  metadata:
    name: jinja-configmap-test
    annotations:
      kustomize.config.k8s.io/needs-hash: "true"
  data:
    username: alice
    password: "{{ data.user }}"
  ---
  kind: ConfigMap
  apiVersion: v1
  metadata:
    name: jinja-configmap-test2
    annotations:
      kustomize.config.k8s.io/needs-hash: "true"
  data:
    username: alice

