apiVersion: someteam.example.com/v1
kind: JinjaTransformer
metadata:
  name: whatever
jinjaCatalog: jinjacatalog.yaml
jinjaTemplate: |
  {% set context = {'resources': resources} %}
  {% for i in functions.filter_getMatchingIndexes(context.resources, 
        functions.filter_operatorAnd(
                functions.filter_fieldExist("kind"), 
                functions.filter_fieldEqual("kind", "ConfigMap"), 
                functions.filter_fieldExist("metadata/name"), 
                functions.filter_operatorOr(
                        functions.filter_fieldEqual("metadata/name", "dev-jinja-configmap-test-v1"), 
                        functions.filter_fieldEqual("metadata/name", "dev-jinja-configmap-test2-v1")))) %}
  {% if context.update({'resources': functions.dict_setByPath(context.resources, "{}/data/username".format(i|string), catalog.data.name_base)}) %}{% endif %}
  {% endfor %}
  {{ functions.yaml_dump(context.resources, _all=True) }}
