apiVersion: someteam.example.com/v1
kind: JinjaTransformer
metadata:
  name: transform-dev-ephemeral-network-data
jinjaCatalog: jinjacatalog.yaml
jinjaTemplate: |
  {% set context = {'resources': functions.dict_deepCopy(resources)} %}
  {% for i in functions.filter_getMatchingIndexes(context.resources, 
        functions.filter_operatorAnd(
                functions.filter_fieldExist("kind"), 
                functions.filter_fieldEqual("kind", "Secret"), 
                functions.filter_fieldExist("metadata/name"), 
                functions.filter_fieldEqual("metadata/name", "dev-node1-bmc-secret-v1"))) %}
  {% if context.update({'resources': functions.dict_setByPath(context.resources, "{}/stringData".format(i|string), catalog.data.name_base)}) %}{% endif %}
  {% endfor %}
  {{ functions.yaml_dumpAll(context.resources) }}
