apiVersion: someteam.example.com/v1
kind: JinjaTransformer
metadata:
  name: transform-dev-ephemeral-network-data
jinjaCatalog: jinjacatalog.yaml
jinjaTemplate: |
  {% set context = {'resources': functions.dict_deepCopy(resources)} %}
  {% for i in functions.filter_getMatchingIndexes(context.resources, 
        functions.filter_operatorAnd(
                functions.filter_fieldExist("kind"), 
                functions.filter_fieldEqual("kind", "Secret"), 
                functions.filter_fieldExist("metadata/name"), 
                functions.filter_fieldEqual("metadata/name", "dev-node1-bmc-secret-v1"))) %}
  {% set corrected_data = functions.dict_setByPath(
                functions.yaml_load(functions.dict_getByPath(context.resources, "{}/stringData/userData".format(i|string))),
                        "ssh_authorized_keys/0",
                        "ssh-rsa {}".format(catalog.data.name_base)) %}
  {% if context.update({'resources': functions.dict_setByPath(
                context.resources, 
                "{}/stringData/userData".format(i|string), 
                functions.yaml_dump(corrected_data)|indent(width=2, first=True))}) %}{% endif %}
  {% endfor %}
  {{ functions.yaml_dumpAll(context.resources) }}
