apiVersion: someteam.example.com/v1
kind: JinjaTransformer
metadata:
  name: transform-dev-ephemeral-network-data2
jinjaCatalog: jinjacatalog.yaml
jinjaTemplate: |
  {% set context = {'resources': resources} %}
  {% for i in functions.filter_getMatchingIndexes(context.resources, 
        functions.filter_operatorAnd(
                functions.filter_fieldEqual("kind", "Secret"), 
                functions.filter_fieldEqual("metadata/name", "dev-node1-bmc-secret-v1"))) %}
  {% if context.update({'resources': functions.dict_setByPath(
                context.resources, 
                "{}/stringData/userData|bootcmd/0".format(i|string), 
                "/usr/sbin/mkfs.ext4 /dev/vda --param {}".format(catalog.data.name_base))}) %}{% endif %}
  {% endfor %}
  {{ functions.yaml_dump(context.resources, _all=True) }}
