apiVersion: someteam.example.com/v1
kind: JinjaTransformer
metadata:
  name: transform-dev-ephemeral-network-data
sources:
- path: jinjacatalog.yaml
jinjaTemplate: |
  {% set context = {'resources': resources} %}
  {% for i in fn.filter_getMatchingIndexes(context.resources,
        fn.filter_operatorAnd(
                fn.filter_fieldExist("kind"),
                fn.filter_fieldEqual("kind", "Secret"),
                fn.filter_fieldExist("metadata/name"),
                fn.filter_fieldEqual("metadata/name", "dev-node1-bmc-secret-v1"))) %}
  {% set corrected_data = fn.dict_modifyByPath(
                fn.yaml_load(fn.dict_getByPath(context.resources, "{}/stringData/userData".format(i|string))),
                        "ssh_authorized_keys/0",
                        fn.operation_set("ssh-rsa {} updated!".format(config.sources[0].object.data.name_base))) %}
  {% if context.update({'resources': fn.dict_modifyByPath(
                context.resources, 
                "{}/stringData/userData".format(i|string), 
                fn.operation_set(fn.yaml_dump(corrected_data)|indent(width=2, first=True)))}) %}{% endif %}
  {% endfor %}
  {{ fn.yaml_dump(context.resources, _all=True) }}
