apiVersion: someteam.example.com/v1
kind: JinjaTransformer
metadata:
  name: transform-dev-ephemeral-network-data2
sources:
- path: jinjacatalog.yaml
jinjaTemplate: |
  {% set context = {'resources': resources} %}
  {% for i in fn.filter_getMatchingIndexes(context.resources,
        fn.filter_operatorAnd(
                fn.filter_fieldEqual("kind", "Secret"),
                fn.filter_fieldEqual("metadata/name", "dev-node1-bmc-secret-v1"))) %}
  {% if context.update({'resources': fn.dict_modifyByPath(
                context.resources, 
                "{}/stringData/userData|bootcmd/0".format(i|string), 
                fn.operation_set(
                        "/usr/sbin/mkfs.ext4 /dev/vda --param {}".format(config.sources[0].object.data.name_base)
                ))}) %}{% endif %}
  {% endfor %}
  {{ fn.yaml_dump(context.resources, _all=True) }}
