apiVersion: someteam.example.com/v1
kind: JinjaGenerator
metadata:
  name: overlay-crypt
data:
  name_base: base_x
  age_base: 25
  user: alixe_base
  # use JINJA_CRYPT_PASSWORD="multipass" to decrypt
  user_encrypted: Z0FBQUFBQmVmQ2Y1TmZoNUh0NWgtVW05OUdjdzFIeF9QY0ZtWjRUWWotY2JGZHdkN2hXc3JzcjlraHNtMjhKOEQyZ18zanMwb25ybzBCeDFVWjhHY2pRUzVyM1BmSXJmZkE9PQ==
jinjaTemplate: |
  apiVersion: {{ config.apiVersion }}
  kind: JinjaCatalog
  metadata:
    name: {{ config.metadata.name }}
  data:
    user_encrypted_new: {{ fn.crypt_encrypt(config.data.user) }}
    user_decrypted: {{ fn.crypt_decrypt(config.data.user_encrypted) }}
    {{ fn.yaml_dump(config.data)|indent(width=2, first=False) }}
