apiVersion: someteam.example.com/v1
kind: JinjaGenerator
metadata:
  name: whatever
sources:
- path: jinjacatalog.yaml
jinjaTemplate: |
  {{ fn.yaml_dump(config.sources[0].object) }}
  ---
  kind: ConfigMap
  apiVersion: v1
  metadata:
    name: jinja-configmap-test
    annotations:
      kustomize.config.k8s.io/needs-hash: "true"
  data:
    username: alice
    password: "{{ config.sources[0].object.data.user }}"
  ---
  kind: ConfigMap
  apiVersion: v1
  metadata:
    name: jinja-configmap-test2
    annotations:
      kustomize.config.k8s.io/needs-hash: "false"
  data:
    username: alice

