apiVersion: someteam.example.com/v1
kind: JinjaTransformer
metadata:
  name: whatever
sources:
- path: jinjacatalog.yaml
jinjaTemplate: |
  {% set context = {'resources': resources} %}
  {% for i in fn.filter_getMatchingIndexes(context.resources,
        fn.filter_operatorAnd(
                fn.filter_fieldExist("kind"),
                fn.filter_fieldEqual("kind", "ConfigMap"),
                fn.filter_fieldExist("metadata/name"),
                fn.filter_operatorOr(
                        fn.filter_fieldEqual("metadata/name", "dev-jinja-configmap-test-v1"),
                        fn.filter_fieldEqual("metadata/name", "dev-jinja-configmap-test2-v1")))) %}
  {% if context.update({'resources': fn.dict_modifyByPath(context.resources, "{}/data/username".format(i|string), fn.operation_set(config.sources[0].object.data.name_base))}) %}{% endif %}
  {% endfor %}
  {{ fn.yaml_dump(context.resources, _all=True) }}
