---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: node01
spec:
  bmc:
    address: redfish+http://172.18.164.36:8000/redfish/v1/Systems/e1d68855-ed7b-43d3-b41e-791b69ccb42a
    credentialsName: node01-bmc
  online: false
  bootMACAddress: 52:54:00:b6:ed:31
  networkData:
    name: node01-netdata
    namespace: default
