apiVersion: someteam.example.com/v1
kind: JinjaCatalog
metadata:
  name: base
data:
  name_base: base_x
  age_base: 25
  user: alixe_base
jinjaTemplate: |
  apiVersion: {{ config.apiVersion }}
  kind: JinjaCatalog
  metadata:
    name: {{ config.metadata.name }}
  data:
    {{ functions.yaml_dump(data)|indent(width=2, first=False) }}
