apiVersion: someteam.example.com/v1
kind: JinjaCatalog
metadata:
  name: overlay-y
parents:
- root: ../crypt
  jinjaCatalog: jinjacatalog.yaml       # jinjacatalog.yaml is default value if omit this param
- jinjaCatalog: arbitrary.yaml          # root isn't changes if it's not set 
data:
  name: x
  age: 25
  user: alixe
  arbitrary:
    a: 10
jinjaTemplate: |
  apiVersion: {{ config.apiVersion }}
  kind: JinjaCatalog
  metadata:
    name: {{ config.metadata.name }}
  data:
    {{ functions.yaml_dump(
        functions.dict_modifyByPath(
                functions.dict_modifyByPath(
                        data, 
                        "", 
                        functions.operation_merge(config.parents[0].obj.data)
                ),
                "arbitrary",
                functions.operation_merge(config.parents[1].obj)
        )
       )|indent(width=2, first=False) }}

