apiVersion: someteam.example.com/v1
kind: JinjaGenerator
metadata:
  name: overlay-y
sources:
- root: ../crypt
  path: jinjacatalog.yaml       # jinjacatalog.yaml is default value if omit this param
- path: arbitrary.yaml          # root isn't changes if it's not set
data:
  name: x
  age: 25
  user: alixe
  arbitrary:
    a: 10
jinjaTemplate: |
  apiVersion: {{ config.apiVersion }}
  kind: JinjaCatalog
  metadata:
    name: {{ config.metadata.name }}
  data:
    {{ fn.yaml_dump(
        fn.dict_modifyByPath(
                fn.dict_modifyByPath(
                        config.data,
                        "", 
                        fn.operation_merge(config.sources[0].object.data)
                ),
                "arbitrary",
                fn.operation_merge(config.sources[1].object)
        )
       )|indent(width=2, first=False) }}

